package uk.gov.digital.ho.hocs.templates.application;

public enum LogEvent {
    CORRESPONDENT_NOT_FOUND,
    UNCAUGHT_EXCEPTION,
    REST_HELPER_POST_FAILURE,
    REST_HELPER_GET,
    REST_HELPER_GET_UNAUTHORIZED,
    REST_HELPER_GET_FORBIDDEN,
    REST_HELPER_GET_NOT_FOUND,
    REST_HELPER_GET_BAD_REQUEST,
    INFO_CLIENT_GET_TEAM_FOR_TOPIC_STAGE_SUCCESS,
    INFO_CLIENT_GET_TEMPLATE_UUID_SUCCESS,
    INFO_CLIENT_GET_TEAM_NOT_FOUND,
    DOCS_CLIENT_GET_TEMPLATE_DATA_SUCCESS,
    DOCS_CLIENT_GET_TEMPLATE_SUCCESS,
    CASE_CLIENT_GET_CASE_DETAILS_SUCCESS,
    CASE_CLIENT_GET_CORRESPONDENT_DETAILS_SUCCESS,
    TEMPLATE_GENERATION_FAILURE;
    public static final String EVENT = "event_id";
    public static final String EXCEPTION = "exception";
}
