name: 'SemVer tag the commit'
on:
  pull_request:
    types: [ closed ]

jobs:
  build:
    name: SemVer tag the commit
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.base_ref == 'main'
    steps:
      - id: label
        uses: UKHomeOffice/match-label-action@main
        with:
          labels: minor,major,patch
          mode: singular
      - uses: UKHomeOffice/semver-tag-action@main
        with:
          increment: ${{ steps.label.outputs.matchedLabels }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
